client_id = "39ac5d68459f69958d6b94369acd0766"
name = "sharecart-pro"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled", "app/scopes_update" ]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks"

[app_proxy]
url = "https://example.com"
subpath = "sharecart"
prefix = "apps"

[access_scopes]
scopes = "read_orders,write_discounts,read_customers,read_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]